### PR TITLE
adding ability to run tests in parallel

### PR DESCRIPTION
**Pull request by korry8911**
@christophermancini to test:

- clone branch
- open multi-test.sh and add your github token, the bento boxes, and the package urls you want to test in the appropriate places
- you can switch between ts and kv tests with the tests variable
- the vmboxes array and the packages array should be the same length... the positions of the elements must correspond to each other... i.e the if the first vmbox is "bento/centos-7.2" then the first package should be a centos7 package

if you run multi-test.sh with only one box/url combo, it will print to stdout, if you run for multiple box/url combos, it will print to a log file in each vm directory

currently there is a bunch of string replacement to configure the ansible playbook properly so maybe we could get strategic and have better strings to match on in the default playbooks

let me know what you think and if you have any suggestions

### CODE REVIEW

**Comment by korry8911** [comment]
@javajolt

**Comment by christophermancini** [comment]
Looks good so far. My only thought is that the time series playbook should default to riak_package = riak-riak-ts, which is the package for package cloud.

**Comment by korry8911** [comment]
so my thinking was that if we have it as riak_package: a_valid_package, it simplifies the sed commands that configure the playbook in multi-test.sh.  We could add comments saying what the options are for riak_package, but I think having a easy token to search and replace s beneficial. Plus, defaults are good, but I think that most of the time the default will not be used since we will be testing new releases that might not be on package cloud. Your thoughts?
Leave as is and add comments highlighting the options for riak packae variable?
Revert back?

@christophermancini

**Comment by christophermancini** [comment]
Then, maybe we should do a timeseries.yml.template like we have for normal KV. Then this playbook still has the defaults available for people who are using it for dev for clients and still gives the testing peeps what they need. Thoughts?

**Comment by korry8911** [comment]
I don't mind having a timeseries.template.yml file but I don't see how this really solves anything.
Currently I have this:
```
# Uncomment following line to use alternate package. Options include URL to RPM or DEB, riak-ts, or a specific version from packagecloud.
    #riak_package: a_valid_package
```

This makes it easy to use sed within multi-test.sh. The comment makes it obvious you could use riak-ts as the package.... the user will have to edit this file anyways (my version or your version) to at least uncomment the line. So i think leaving it like this doesn't really hurt anything and makes it easier to have a script, like mutli-test.sh to configure the playbook.

**Review by christophermancini — APPROVED** [review]
Looks good. Thanks!

**Pull request merged**
